config/routes.rb
Hardwareto::Application.routes.draw do

  root :to => 'pages#index'

  get "pages/index"
  match "about"     => "pages#about"
  match "events"     => "pages#events"
  match "calendars" => "pages#calendars"
  match "subscribe" => "pages#subscribe"
  match "*a", :to => "errors#not_found"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

	def not_found
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@body_class = "landing site"
  end

  def about
  	@body_class = "about site"
  end

  def event
  	@body_class = "pricing site"
  end

  def subscribe
  	@body_class = "pricing site"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!D`YPE html>
<html>
<head>
  <title>Hardwareto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= @body_class %>">
    

<div class="navbar">
    <div class="container">
        <a class="navbar-brand" href="/">
        <%= image_tag("logo.png", width: "220", :alt => "HardwareTO" )%>
        </a>
        <ul class="nav navbar-nav">
            <li><a href="<%= about_path %>" class="nav-about">About</a></li>
            <li><a href="http://blog.hardwareto.com" class="nav-blog">Blog</a></li>
            <li class="sep"></li>
            
            <li class="signup"><a href="<%= subscribe_path %>" class="btn signup-link">Subscribe to Mailing List</a></li>
            
        </ul>
    </div>
</div>

<%= yield %>
<footer>

    <div class="container">
        <div class="row">
            
            <div class="col col-lg-1">
            <%= image_tag("hto_logo.png", alt: "hardwareTO", width: "82", style: "opacity:0.15") %>
            </div>
            
            <div class="col col-lg-9">
                <a href="/about/">About</a>
                <a href="http://blog.hardwareto.com">Blog</a>
                <div style="padding:0 20px; vertical-align:middle; display:inline-block"><a href="https://twitter.com/hardwareTO" class="twitter-follow-button" data-show-count="false">Follow @hardwareTO</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                </div>
            </div>
            <div class="col col-lg-2">
                <span>&copy 2013 - <a href="https://kippt.com/">HardwareTO</a></span>
            </div>
        </div>
    </div>

</footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42777559-1', 'hardwareto.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="background">
    <h1>ABOUT HTO</h1>
</div>
<article class="container">
    <section class="col col-lg-6 col-offset-3">
        <blockquote>
            <p>“People who are really serious about software should make their own hardware.”
            </p>
            &mdash; Alan Kay 
        </blockquote>
        <hr>
        <p>HardwareTO is a bi-annual Meetup happening in Toronto for Hardware Startups in Canada. It is filled with drinks, shirts, prizes and amazing products you get to play with. You also get the chance to hear motivational speech from some of the best hardware startup entrepreneurs.
        </p>

        <hr>
        <p>Questions? <a href="mailto:info@hardwareto.com">Email us</a> or <a href="https://twitter.com/hardwareTO">tweet us</a></p>

    </section>

</article>

app/views/pages/events.html.erb
<article id="pricing">

    <section class="container box">
        <header>
            <h1>Workshops and Classes</h1>
            <p class="lead">Attend an event or start one</p>
        </header>

        <div class="col col-lg-6">
            <h4>Next Event</h4>
            <p class="price"><strong>TBA</strong></p>
        </div>

        <div class="col col-lg-6 start">
            <h3>Become A Mentor</h3>
            <a href="/login/google-oauth2/" class="btn btn-primary">Start A Workshop</a><br>
            <p>or <a href="/accounts/signup/">recommomend someone</a></p>
        </div>

    </section>

</article>

app/views/pages/index.html.erb
    <header>
        <div class="bg"></div>
        <div class="container">
            <h1>Toronto Hardware Startup Meetup</h1>
            <p>Bringing Makers & Developers Together</p>
            <a href="http://meetup.com/HardwareTO" class="btn btn-primary signup-link">Join Our Meetup</a>
        </div>
    </header>


    <section id="work">
        <div class="container">
            <h2>Next Event: October 2nd, 2013</h2><br/>
            <a href="http://hardwareto.eventbrite.com/" class="attend">Attend</a><br><br>
        </div>

        
        <div class="container">
            <div class="row"><br><br>
            <h3>Why you should come?</h3>
                <div class="col col-lg-4">
                    <h4>Grow your Network</h4>
                    <p>We invite top influencers in the tech field to our events: startups and their founders, product makers, developers and members of the media.</p>
                </div>
                <div class="col col-lg-4">
                    <h4>Try New Products</h4>
                    <p>Come and try the products of the 5 startups we invite. Startup get to have a booth or stands and showcase
                    their product.</p>
                </div>
                <div class="col col-lg-4">
                    <h4>Short Demo</h4>
                    <p>We want our events to help you meet new people and have a lot of fun. Hear two minute elevator pitches from the five exciting hardware startups we invite to our event</p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <h4>Build Your Team</h4>
                    <p>This event brings bright minds together it is a great opportunity to find your next co-founder, team member or talented hire.</p>
                </div>
                <div class="col col-lg-4">
                    <h4>Speaker</h4>
                    <p>We work through our network to bring you the most talented people from Silicon Valley and from all over North America to motivate and inspire you with talk on interesting topics. </p>
                </div>
                <div class="col col-lg-4">
                    <h4>Free Drinks!</h4>
                    <p>Our drinks are generously provided by Upverter. We also work with our awesome network of partners to provide you with free goodies and T-shirts</p>
                </div>
            </div>
        </div>

    </section>

    <section id="howto">

<!--         <h3>Gold Sponsor</h3>
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("your_logo.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("your_logo.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("your_logo.png")%>
                    </div>
                </div>
            </div>
        </div>

        <h3>Silver Sponsor</h3>
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("your_logo.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("your_logo.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("your_logo.png")%>
                    </div>
                </div>
            </div>
        </div> -->

        <h3>Community Partner</h3>
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("richdxstudio.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("sponsors/upverter_logo.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("Bitmaker-Labs.jpg")%>
                    </div>
                </div>
            </div>
        </div>

        <h3>Services Provider</h3>
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("http://ebmedia.eventbrite.com/s3-build/15498-rc2013-07-22-5af2e91/django/images/logos/eb_home_tm-trans.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("your_logo.png")%>
                    </div>
                </div>
                <div class="col col-lg-4">
                    <div>
                        <%= image_tag("http://blog.newrelic.com/wp-content/uploads/heroku_logo.png")%>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
        	<p>We are really grateful to individuals, companies and organization that support us and make this possible.</p>
        	<div>Become our next sponsor. Request our <a href="info@hardwareto.com">Sponsor Package</a> or <a href="info@hardwareto.com">Email Us</a></div>
        </div>
    </section>

    <section id="testimonials">
        <h2>What people say about HardwareTO</h2>
        <div class="container">
        <div class="row">
        <!-- Add SnapWidget for instagram widget -->
		<a class="twitter-timeline" href="https://twitter.com/search?q=hardwareTO" data-widget-id="362087944342876160">Tweets about "hardwareTO"</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

		</div>
    </section>

app/views/pages/subscribe.html.erb
<article id="pricing">

    <section class="container box">
        <header>
            <h1>Mailing List</h1>
            <p class="lead">Subscribe to our mailing and stay up to date! We promise we won't spam you.</p>
        </header>


        <div class="col col-lg-12 start">
        <!-- Begin MailChimp Signup Form -->
        <style type="text/css">
            #mc_embed_signup input.email {
            width: 355px;
            margin-left: 27%;
            }
            input#mc-embedded-subscribe{width: 356px;}
            /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
               We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
        </style>
        <div id="mc_embed_signup">
        <form action="http://richdx.us5.list-manage1.com/subscribe/post?u=47e7679c4c3bf939e72289116&amp;id=ec24eccbfa" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <label for="mce-EMAIL"></label>
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button btn btn-primary">
        </form>
        </div>
        <!--End mc_embed_signup-->
        </div>
        
    </section>

</article>